"use client";
import Image from "next/image";
import {useEffect,useState} from "react";
import {AtSign as Instagram,Clock3,MapPin,MessageCircle,Star,X} from "lucide-react";
import {money} from "@/lib/utils";

export type MenuProduct={id:string;name:string;description:string;priceCents:number;imageUrl:string;available:boolean;featured:boolean;categoryName:string};
export type MenuCategory={id:string;name:string;slug:string;products:MenuProduct[]};
type Settings={restaurantName:string;description:string;whatsapp:string;instagram:string;address:string;openingHours:string};

function ProductImage({product,className}:{product:MenuProduct;className:string}){
  return product.imageUrl?<Image src={product.imageUrl} alt={product.name} fill sizes="(max-width: 768px) 90vw, 420px" className={`object-cover ${className}`}/>:<div className={`grid place-items-center bg-[var(--wine-dark)] text-xs uppercase tracking-widest text-[var(--muted)] ${className}`}>Sem foto</div>;
}

export function MenuExperience({categories,settings}:{categories:MenuCategory[];settings:Settings}){
  const [selected,setSelected]=useState<MenuProduct|null>(null);
  const featured=categories.flatMap(category=>category.products).filter(product=>product.featured);
  const hasProducts=categories.some(category=>category.products.length);
  useEffect(()=>{document.body.style.overflow=selected?"hidden":"";return()=>{document.body.style.overflow=""}},[selected]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&setSelected(null);window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  return <>
    {categories.length>0&&<nav className="sticky top-0 z-40 border-b border-[var(--border)] bg-[rgba(8,4,4,.9)] backdrop-blur-xl" aria-label="Categorias"><div className="site-container scrollbar-none flex gap-2 overflow-x-auto py-3">{categories.map(category=><a key={category.id} href={`#${category.slug}`} className="shrink-0 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-4 py-2 text-sm font-bold text-[var(--text-secondary)] transition hover:border-[var(--primary)] hover:text-white focus-visible:text-white">{category.name}</a>)}</div></nav>}
    <main className="site-container py-10 sm:py-14">
      {featured.length>0&&<section className="mb-14"><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Seleção especial</p><h2 className="display-font mt-2 text-3xl font-bold uppercase sm:text-4xl">Favoritos da casa</h2></div><Star size={22} className="text-[var(--primary)]"/></div><div className="scrollbar-none -mx-4 flex snap-x gap-4 overflow-x-auto px-4 pb-2 sm:mx-0 sm:grid sm:grid-cols-2 sm:px-0 lg:grid-cols-3">{featured.map(product=><button key={product.id} onClick={()=>setSelected(product)} className="group min-w-[82vw] snap-start overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)] text-left transition hover:-translate-y-1 hover:border-[var(--border-strong)] sm:min-w-0"><div className="relative aspect-[16/10] overflow-hidden"><ProductImage product={product} className="transition duration-300 group-hover:scale-[1.03]"/>{!product.available&&<span className="absolute left-4 top-4 status status-primary">Esgotado</span>}</div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">{product.categoryName}</p><h3 className="mt-1 text-xl font-bold">{product.name}</h3><p className="line-clamp-2 mt-2 min-h-10 text-sm leading-relaxed text-[var(--text-secondary)]">{product.description||"Confira os detalhes deste item."}</p><p className="mt-4 text-lg font-extrabold text-[var(--primary)]">{money(product.priceCents)}</p></div></button>)}</div></section>}
      {!hasProducts?<section className="surface empty-state"><div><p className="eyebrow">Em breve</p><h2 className="display-font mt-3 text-3xl font-bold uppercase">Nosso cardápio está sendo atualizado</h2><p className="mx-auto mt-3 max-w-lg text-[var(--text-secondary)]">Estamos preparando tudo com carinho. Volte em alguns instantes para conferir nossas opções.</p></div></section>:categories.map(category=>category.products.length>0&&<section id={category.slug} className="mb-16 scroll-mt-24" key={category.id}><div className="mb-6"><p className="eyebrow">Cardápio</p><h2 className="display-font mt-2 text-3xl font-bold uppercase sm:text-4xl">{category.name}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">Escolha um item para ver todos os detalhes.</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{category.products.map(product=><button key={product.id} onClick={()=>setSelected(product)} className={`group flex min-h-40 overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)] text-left transition hover:-translate-y-0.5 hover:border-[var(--border-strong)] ${!product.available?"opacity-65":""}`}><div className="flex min-w-0 flex-1 flex-col p-5"><div className="flex items-start gap-2"><h3 className="line-clamp-2 flex-1 text-lg font-bold leading-snug">{product.name}</h3>{!product.available&&<span className="status status-primary">Esgotado</span>}</div><p className="line-clamp-2 mt-2 text-sm leading-relaxed text-[var(--text-secondary)]">{product.description||"Toque para ver os detalhes."}</p><p className="mt-auto pt-4 font-extrabold text-[var(--primary)]">{money(product.priceCents)}</p></div><div className="relative w-32 shrink-0 overflow-hidden sm:w-36"><ProductImage product={product} className="transition duration-300 group-hover:scale-105"/></div></button>)}</div></section>)}
    </main>
    <footer className="border-t border-[var(--border)] bg-[var(--surface)]"><div className="site-container grid gap-6 py-10 sm:grid-cols-2"><div><p className="display-font text-xl font-bold uppercase">{settings.restaurantName}</p>{settings.description&&<p className="mt-2 max-w-md text-sm leading-relaxed text-[var(--text-secondary)]">{settings.description}</p>}</div><div className="grid gap-2 text-sm text-[var(--text-secondary)] sm:justify-self-end">{settings.openingHours&&<p className="flex items-center gap-2"><Clock3 size={15}/>{settings.openingHours}</p>}{settings.address&&<p className="flex items-center gap-2"><MapPin size={15}/>{settings.address}</p>}{settings.instagram&&<p className="flex items-center gap-2"><Instagram size={15}/>{settings.instagram}</p>}{settings.whatsapp&&<p className="flex items-center gap-2"><MessageCircle size={15}/>{settings.whatsapp}</p>}</div></div></footer>
    {selected&&<div className="dialog-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&setSelected(null)}><section className="product-dialog" role="dialog" aria-modal="true" aria-labelledby="product-title"><button className="btn btn-secondary icon-btn absolute right-4 top-4 z-10 !rounded-full" onClick={()=>setSelected(null)} aria-label="Fechar detalhes"><X size={20}/></button><div className="relative aspect-[16/10] min-h-64 overflow-hidden bg-[var(--wine-dark)]"><ProductImage product={selected} className=""/>{!selected.available&&<div className="absolute inset-0 grid place-items-center bg-black/45"><span className="status status-primary text-sm">Esgotado</span></div>}</div><div className="p-6 sm:p-8"><p className="eyebrow">{selected.categoryName}</p><h2 id="product-title" className="display-font mt-2 text-3xl font-bold uppercase sm:text-4xl">{selected.name}</h2><p className="mt-4 leading-relaxed text-[var(--text-secondary)]">{selected.description||"Sem descrição cadastrada."}</p><div className="mt-7 flex items-center justify-between border-t border-[var(--border)] pt-6"><p className="text-2xl font-extrabold text-[var(--primary)]">{money(selected.priceCents)}</p><button className="btn btn-secondary" onClick={()=>setSelected(null)}>Fechar</button></div></div></section></div>}
  </>;
}
