"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState} from "react";
import {ExternalLink,FolderOpen,LayoutDashboard,LogOut,Menu,Settings,UtensilsCrossed,X} from "lucide-react";
import {Brand} from "@/components/brand";

const links=[{href:"/admin",label:"Resumo",icon:LayoutDashboard},{href:"/admin/produtos",label:"Produtos",icon:UtensilsCrossed},{href:"/admin/categorias",label:"Categorias",icon:FolderOpen},{href:"/admin/configuracoes",label:"Configurações",icon:Settings}];
function Navigation({pathname,onNavigate,signout}:{pathname:string;onNavigate?:()=>void;signout:()=>Promise<void>}){return <div className="flex h-full flex-col"><Link href="/admin" onClick={onNavigate} className="mb-9"><Brand compact/></Link><nav className="grid gap-1">{links.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={onNavigate} className={`admin-nav-link ${pathname===href||href!=="/admin"&&pathname.startsWith(href)?"active":""}`}><Icon size={18}/>{label}</Link>)}</nav><div className="mt-auto grid gap-1 border-t border-[var(--border)] pt-5"><Link href="/" target="_blank" className="admin-nav-link"><ExternalLink size={18}/>Ver cardápio</Link><form action={signout}><button className="admin-nav-link w-full"><LogOut size={18}/>Sair</button></form></div></div>}
export function AdminShell({children,signout}:{children:React.ReactNode;signout:()=>Promise<void>}){const pathname=usePathname();const [open,setOpen]=useState(false);return <div className="admin-shell"><aside className="admin-sidebar"><Navigation pathname={pathname} signout={signout}/></aside><header className="mobile-topbar"><Brand compact/><button className="btn btn-secondary icon-btn" onClick={()=>setOpen(true)} aria-label="Abrir menu"><Menu size={20}/></button></header>{open&&<div className="mobile-drawer" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><aside className="mobile-drawer-panel"><div className="mb-4 flex justify-end"><button className="btn btn-ghost icon-btn" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X size={20}/></button></div><Navigation pathname={pathname} signout={signout} onNavigate={()=>setOpen(false)}/></aside></div>}<div className="admin-main">{children}</div></div>}
