import Image from "next/image";
import Link from "next/link";
import {ArrowRight,FolderOpen,Plus,UtensilsCrossed} from "lucide-react";
import {prisma} from "@/lib/prisma";
import {money} from "@/lib/utils";

export default async function Page(){
  const [products,categories,available,recent,settings]=await Promise.all([prisma.product.count(),prisma.category.count(),prisma.product.count({where:{available:true}}),prisma.product.findMany({take:5,orderBy:{updatedAt:"desc"},include:{category:true}}),prisma.restaurantSettings.findUnique({where:{id:"default"}})]);
  const metrics=[["Produtos",products,UtensilsCrossed],["Categorias",categories,FolderOpen],["Disponíveis",available,UtensilsCrossed],["Esgotados",products-available,UtensilsCrossed]] as const;
  return <main className="admin-container admin-page"><header className="page-header"><div><p className="eyebrow">Painel administrativo</p><h1 className="page-title mt-2">Resumo do cardápio</h1><p className="page-description">Acompanhe e mantenha o cardápio de {settings?.restaurantName??"Jantinha do Rogério"} atualizado.</p></div><Link href="/admin/produtos/novo" className="btn btn-primary shrink-0"><Plus size={18}/>Novo produto</Link></header><section className="metric-grid">{metrics.map(([label,value,Icon])=><article className="admin-card metric-card" key={label}><div className="flex items-center justify-between text-sm text-[var(--text-secondary)]"><span>{label}</span><Icon size={17}/></div><p className="metric-value">{value}</p></article>)}</section><section className="admin-section"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">Produtos recentes</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">Últimos itens atualizados no cardápio.</p></div><Link href="/admin/produtos" className="btn btn-ghost">Ver todos <ArrowRight size={16}/></Link></div><div className="admin-card">{recent.length?recent.map(product=><div className="flex items-center gap-4 border-b border-[var(--border)] p-4 last:border-0" key={product.id}><div className="admin-thumb">{product.imageUrl&&<Image src={product.imageUrl} alt="" fill sizes="64px" className="object-cover"/>}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{product.name}</p><p className="mt-1 text-xs text-[var(--text-secondary)]">{product.category.name} · {money(product.priceCents)}</p></div><span className={`status ${product.available?"status-success":"status-muted"}`}>{product.available?"Disponível":"Esgotado"}</span></div>):<div className="empty-state"><div><UtensilsCrossed className="mx-auto text-[var(--primary)]"/><h3 className="mt-4 text-xl font-bold">Seu cardápio ainda está vazio</h3><p className="mt-2 text-sm text-[var(--text-secondary)]">Cadastre o primeiro item para começar.</p><Link href="/admin/produtos/novo" className="btn btn-primary mt-5"><Plus size={17}/>Adicionar produto</Link></div></div>}</div></section></main>;
}
